package segundo.modelos;
// Generated 22/03/2021 06:50:53 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Publicaciones generated by hbm2java
 */
public class Publicaciones  implements Serializable {


     private int id;
     private Boolean visible;
     private String texto;
     private String hora;
     private Date fecha;
     private Set usuarioses = new HashSet(0);

    public Publicaciones() {
    }

	
    public Publicaciones(int id) {
        this.id = id;
    }
    public Publicaciones(int id, Boolean visible, String texto, String hora, Date fecha, Set usuarioses) {
       this.id = id;
       this.visible = visible;
       this.texto = texto;
       this.hora = hora;
       this.fecha = fecha;
       this.usuarioses = usuarioses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Boolean getVisible() {
        return this.visible;
    }
    
    public void setVisible(Boolean visible) {
        this.visible = visible;
    }
    public String getTexto() {
        return this.texto;
    }
    
    public void setTexto(String texto) {
        this.texto = texto;
    }
    public String getHora() {
        return this.hora;
    }
    
    public void setHora(String hora) {
        this.hora = hora;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set usuarioses) {
        this.usuarioses = usuarioses;
    }

}


