
package segundo.GUI;

import javax.swing.JDesktopPane;
import segundo.Segundo;

/**
 *
 * @author zelmo
 */
public class MDIprincipal extends javax.swing.JFrame implements MetodosBasicos{

    public MDIprincipal() {
        initComponents();
        hBotones(false,false,false,false,false);
    }
    public static void iVentanas(){
        Segundo.ru = new RegistroUsuarios();
        Segundo.mdi.desktopPane.add(Segundo.ru);
        //Main.ru.hide();
    }
    
    public void hBotones(Boolean c,Boolean g,Boolean ca,Boolean u,Boolean b){
        this.becrear.setEnabled(c);
        this.beguardar.setEnabled(g);
        this.becancelar.setEnabled(ca);
        this.beupdate.setEnabled(u);
        this.beborrar.setEnabled(b);
    }
        
    public JDesktopPane destop(){
        return this.desktopPane;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        becrear = new javax.swing.JButton();
        beguardar = new javax.swing.JButton();
        becancelar = new javax.swing.JButton();
        beupdate = new javax.swing.JButton();
        beborrar = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        salirMDI = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        AbrirRegistro = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Red Social");
        setAlwaysOnTop(true);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        desktopPane.setPreferredSize(new java.awt.Dimension(800, 600));

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setMaximumSize(new java.awt.Dimension(361, 150));

        becrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/nuevo.png"))); // NOI18N
        becrear.setText("Nueva cuenta");
        becrear.setFocusable(false);
        becrear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        becrear.setMaximumSize(new java.awt.Dimension(73, 150));
        becrear.setPreferredSize(new java.awt.Dimension(73, 150));
        becrear.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        becrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                becrearActionPerformed(evt);
            }
        });
        jToolBar1.add(becrear);

        beguardar.setText("Guardar datos");
        beguardar.setFocusable(false);
        beguardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        beguardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        beguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beguardarActionPerformed(evt);
            }
        });
        jToolBar1.add(beguardar);

        becancelar.setText("Cancelar");
        becancelar.setFocusable(false);
        becancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        becancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        becancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                becancelarActionPerformed(evt);
            }
        });
        jToolBar1.add(becancelar);

        beupdate.setText("Actualizar datos");
        beupdate.setFocusable(false);
        beupdate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        beupdate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        beupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beupdateActionPerformed(evt);
            }
        });
        jToolBar1.add(beupdate);

        beborrar.setText("Eliminar cuenta");
        beborrar.setFocusable(false);
        beborrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        beborrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        beborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beborrarActionPerformed(evt);
            }
        });
        jToolBar1.add(beborrar);

        menuBar.setPreferredSize(new java.awt.Dimension(81, 27));

        fileMenu.setMnemonic('f');
        fileMenu.setText("archivo");

        salirMDI.setMnemonic('o');
        salirMDI.setText("Salir");
        salirMDI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirMDIActionPerformed(evt);
            }
        });
        fileMenu.add(salirMDI);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Aplicación");

        AbrirRegistro.setMnemonic('t');
        AbrirRegistro.setText("Registro");
        AbrirRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbrirRegistroActionPerformed(evt);
            }
        });
        editMenu.add(AbrirRegistro);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Ayuda");
        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirMDIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirMDIActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirMDIActionPerformed

    private void AbrirRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbrirRegistroActionPerformed
        Segundo.ru.activar();
    }//GEN-LAST:event_AbrirRegistroActionPerformed

    private void becrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_becrearActionPerformed
        nuevo();
    }//GEN-LAST:event_becrearActionPerformed

    private void beguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beguardarActionPerformed
        guardar();
    }//GEN-LAST:event_beguardarActionPerformed

    private void becancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_becancelarActionPerformed
        cancelar();
    }//GEN-LAST:event_becancelarActionPerformed

    private void beupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beupdateActionPerformed
        editar();
    }//GEN-LAST:event_beupdateActionPerformed

    private void beborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beborrarActionPerformed
        borrar();
    }//GEN-LAST:event_beborrarActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AbrirRegistro;
    private javax.swing.JButton beborrar;
    private javax.swing.JButton becancelar;
    private javax.swing.JButton becrear;
    private javax.swing.JButton beguardar;
    private javax.swing.JButton beupdate;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem salirMDI;
    // End of variables declaration//GEN-END:variables

    @Override
    public void nuevo() {
        MetodosBasicos mb = (MetodosBasicos) this.desktopPane.getSelectedFrame();
        if(mb != null){
            mb.nuevo();
        }
    }

    @Override
    public void guardar() {
        MetodosBasicos mb = (MetodosBasicos) this.desktopPane.getSelectedFrame();
        if(mb != null){
            mb.guardar();
        }
    }

    @Override
    public void cancelar() {
        MetodosBasicos mb = (MetodosBasicos) this.desktopPane.getSelectedFrame();
        if(mb != null){
            mb.cancelar();
        }
    }

    @Override
    public void editar() {
        MetodosBasicos mb = (MetodosBasicos) this.desktopPane.getSelectedFrame();
        if(mb != null){
            mb.editar();
        }
    }

    @Override
    public void borrar() {
        MetodosBasicos mb = (MetodosBasicos) this.desktopPane.getSelectedFrame();
        if(mb != null){
            mb.borrar();
        }
    }

    @Override
    public void salir() {
        MetodosBasicos mb = (MetodosBasicos) this.desktopPane.getSelectedFrame();
        if(mb != null){
            mb.salir();
        }
    }

    @Override
    public void activar() { }
}
